"""UI smoke test — boots the real Kivy app and drives every screen.

Run on a machine with Kivy installed (the Windows desktop Python is enough):

    pip install kivy
    python android/smoke_test.py

A Kivy window flashes for about a second, then the app closes itself and the
checks are printed. Exit code is non-zero if anything fails, so it doubles as a
regression test for the Android UI (a broken APK usually shows up here first —
e.g. a method that shadows `App.run()` kills the app before any window opens).
"""
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

# core_nest.py is generated by package_apk.sh; make it importable from a clean
# checkout too.
if not os.path.exists(os.path.join(HERE, "core_nest.py")):
    shutil.copy(os.path.join(HERE, os.pardir, "src", "core_nest.py"), HERE)

from kivy.clock import Clock          # noqa: E402
from kivy.core.window import Window   # noqa: E402

import main as m                      # noqa: E402


def check(label, cond):
    print(("PASS  " if cond else "FAIL  ") + label, flush=True)
    if not cond:
        raise AssertionError(label)


def close_popups():
    for w in [x for x in Window.children if hasattr(x, "dismiss")]:
        w.dismiss()


def popup_count():
    return len([x for x in Window.children if hasattr(x, "dismiss")])


def labels(widget):
    for ch in widget.children:
        if isinstance(ch, m.Label):
            yield ch.text
        yield from labels(ch)


def step(dt):
    app = m.CutMitraApp.get_running_app()
    check("app instance is CutMitraApp", isinstance(app, m.CutMitraApp))
    check("root widget exists", app.root is not None)
    check("5 tabs", len(app.tabs.tab_list) == 5)

    app.kerf_in.text = "3"
    app.trim_in.text = "0"
    app.start_nesting()
    check("29 sheets nested", len(app.sheets) == 29)
    check("summary shown", "Sheets: 29" in app.res_label.text)
    check("80.09% util", "80.09%" in app.res_label.text)
    check("switched to RESULT", app.tabs._current_tab is app.tab_o)
    check("sheet label", app.sheet_label.text == "Sheet 1/29")
    check("cut list rendered", len(app.cut_label.text.splitlines()) > 3)

    app.step_sheet(1)
    check("sheet 2", app.sheet_label.text == "Sheet 2/29")
    app.step_sheet(-1)
    check("back to sheet 1", app.sheet_label.text == "Sheet 1/29")
    app.step_sheet(-99)
    check("clamped at 1", app.sheet_label.text == "Sheet 1/29")

    app.tabs.switch_to(app.tab_a)
    about = "\n".join(labels(app.tabs.content))
    check("ABOUT has credits", "Er. Durgesh Pandey" in about
          and "Er. Arun Shukla" in about)
    check("ABOUT has version", m.VERSION in about)

    app.open_editor("demand", 0)
    check("edit popup opened", popup_count() >= 1)
    close_popups()
    app.open_editor("stock", -1)
    check("add popup opened", popup_count() >= 1)
    close_popups()

    app.delete_row("demand", 0)
    check("row deleted", len(app.demands) == 0)
    app.start_nesting()
    check("error popup on empty demand", popup_count() >= 1)
    close_popups()

    app.clear_list("stock")
    app.start_nesting()
    check("error popup on empty stock", popup_count() >= 1)
    close_popups()

    app.demands = [
        {"L": 380.0, "W": 955.0, "qty": 200, "rot": True, "grain": False,
         "material": "MS", "label": ""},
        {"L": 610.0, "W": 410.0, "qty": 60, "rot": True, "grain": False,
         "material": "MS", "label": ""},
    ]
    app.stocks = [{"L": 1250.0, "W": 2500.0, "qty": 200, "material": "MS",
                   "label": "", "price": 850.0}]
    app.refresh_lists()
    app.start_nesting()
    check("multi-material run nested", len(app.sheets) > 0)
    check("material-wise block", "[MS]" in app.res_label.text)
    check("cost shown", "Cost:" in app.res_label.text)

    print("\nALL UI CHECKS PASSED", flush=True)
    app.stop()


class _TestApp(m.CutMitraApp):
    def build(self):
        root = super().build()
        Clock.schedule_once(step, 1.0)
        return root


_TestApp().run()
print("SMOKE TEST FINISHED", flush=True)
